### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by claunia** [tenox7/wrp#10]
Some pages will stop, or are not, supporting HTTP anymore. WRP should handle the HTTPS protocol itself for browsers that predate the adequate SSL/TLS versions like MSIE 1.5 and Mosaic.

**Comment by tenox7** [comment]
Auto accept invalid SSL certificates such as self-signed certificates.

**Comment by tjabring** [comment]
YEP! I can confirm..many people ask for HTTPS support!

**Comment by sigtau** [comment]
Is this project still active, and if so, what was the status on this particular feature?

**Comment by tenox7** [comment]
Yes the project is still active however detailed a more evaluation proved that SSL support is much more difficult that originally anticipated. I'm working on it though.

**Comment by girst** [comment]
@tenox7, I've had good results just proxying `wrp`'s connection through `sslstrip`.
```diff
+    subprocess.Popen(["sslstrip"], stdout=open(os.devnull,'w'), stderr=subprocess.STDOUT) # runs on port 10000 by default
+    QNetworkProxy.setApplicationProxy(QNetworkProxy(QNetworkProxy.HttpProxy, "localhost", 10000))
     threading.Thread(target=run_proxy).start()
```

**Comment by tenox7** [comment]
Wow this sounds great. Could you make a PR for this?

**Comment by tenox7** [comment]
Thanks! Can you make it to a configurable option? eg SSLSTRIP=True|False

**Comment by mactjaap** [comment]
Wowww surfing with retro computers and break the ssl barier! That would be cool.

Not sure how to get this working.... Testing on Firefox.
I tried it and it starts up stripssl, but it trows 501 errors:

192.168.178.2 - - [01/Jan/2019 15:48:49] code 501, message Unsupported method ('CONNECT')
192.168.178.2 - - [01/Jan/2019 15:48:49] "CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1" 501 -
192.168.178.2 - - [01/Jan/2019 15:48:49] code 501, message Unsupported method ('CONNECT')
192.168.178.2 - - [01/Jan/2019 15:48:49] "CONNECT incoming.telemetry.mozilla.org:443 HTTP/1.1" 501 -
192.168.178.2 - - [01/Jan/2019 15:48:55] code 501, message Unsupported method ('POST')

**Comment by tenox7** [comment]
Try a web browser without HTTP 1.1 support.

**Comment by tenox7** [comment]
sslstrip is working okish, cdp version will also support ssl natively, closing this
