### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by itsaidendipier-ro** [tenox7/wrp#100]
I downloaded wrp-amd64 and I don't know how to use it for Windows 98SE. I put the file into disk burn then put it into W98 and then clicked on it and I get a message "a device attached to the system is not functioning" and before that message "The D:\WRP-AMD64-Windows.exe was not compiled for this version of windows." Please tell me how to use thanks!

**Comment by TheTechRobo** [comment]
This is a proxy. You install it on another computer, connect Windows 98 SE to the local network, and then connect to the other compuyter

**Comment by tenox7** [comment]
Thank you for your help! Please refer to the first point of the readme doc [Download a WRP binary](https://github.com/tenox7/wrp/releases/) and run it on a machine that will become your WRP gateway/server. This machine should be pretty modern, high spec and Google Chrome / Chromium Browser is required to be preinstalled.
