### ISSUE TITLE
help this doesnt work in windows xp

### ISSUE THREAD

**Issue by juanroman74454811** [tenox7/wrp#104]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
![bandicam 2022-12-10 00-30-12-934](https://user-images.githubusercontent.com/92176733/206827078-ceb674da-6fa5-48b6-8111-1f520c8b8463.jpg)

i think this is the error i got lawl

**Comment by juanroman74454811** [comment]
> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ![bandicam 2022-11-25 01-13-01-324](https://user-images.githubusercontent.com/92176733/206827055-eafdf4af-acce-48a1-a00e-ee2a597a42cb.jpg) i think this is the error i got lawl
wait wrong image
![bandicam 2022-12-10 00-30-12-934](https://user-images.githubusercontent.com/92176733/206827070-3b21af6b-ad59-4b2c-ab66-4accbba65fa1.jpg)

**Comment by tenox7** [comment]
What machine type and OS is this?
