### ISSUE TITLE
Docker image still at 4.6.3

### ISSUE THREAD

**Issue by fergycool** [tenox7/wrp#117]
Well done for adding the new reader/markdown mode.
However, the Docker image appears to be still at 4.6.3.
The version shown in the rendered page shows 4.6.3 at the bottom. Plus if I access the container and run wrp manually it shows "Web Rendering Proxy Version 4.6.3".
Do I have to build the image manually?
Thanks!

**Comment by tenox7** [comment]
thank you for reporting it, probably a mistake, I forgot to bump the version in docker image
let me see if I can fix it

**Comment by tenox7** [comment]
Pushed 4.7.1 to Docker Hub. Let me know if this doesn't work. I will test it as well.

**Comment by fergycool** [comment]
Thanks. updated to 4.7.1. Images work fine. However, "text" mode does not. I will enter a new bug.
