### ISSUE TITLE
./wrp.go:452:6: rq.captureMarkdown undefined 

### ISSUE THREAD

**Issue by spz2020** [tenox7/wrp#118]
![Screenshot_2024-07-04-01-24-26-98_84d3000e3f4017145260f7618db1d683](https://github.com/tenox7/wrp/assets/74664513/94d220a1-46d7-4280-be2f-785ee4644cf8)

**Comment by tenox7** [comment]
thank you for reporting this!
there was a bug in makefile, just fixed it!!
