### ISSUE TITLE
Text mode: Use urls that start with "/?" instead of just "?"

### ISSUE THREAD

**Issue by mallardtheduck** [tenox7/wrp#119]
Some ancient web browsers (I was testing with a version of NCSA Mosaic 2.8) don't interpret the urls starting with "?" as being relative the way more modern browsers do. Would it be possible to output the urls in text mode as "/?" which should be more compatible? 

That is how the "version" link at the bottom of every page is formed.

**Comment by tenox7** [comment]
yeah good catch! thank you!

**Comment by tenox7** [comment]
made a minor release 4.7.1 with this fix, hope it works
