### ISSUE TITLE
The new "text" mode gives a certificate error.

### ISSUE THREAD

**Issue by fergycool** [tenox7/wrp#120]
With 4.7.1 the three image options work fine. However, with the new "TEXT" option I get the following error: 

    "Get 'https://scotgate.org' : tls: failed to verify certificate:x509: certificate signed by unknown authority"

I tested with a few websites with the same error.

**Comment by tenox7** [comment]
ah thank you! a good catch

should be an easy fix

**Comment by tenox7** [comment]
are these specific websites with cert errors?

do well known websites like cnn.com or github.com work ok?

**Comment by fergycool** [comment]
My apologies as that was not a particularly detailed bug report! As well as the URL in the initial bug report (my blog.. sorry!), I'd tried google.com and a few others I cannot remember. All gave the error. I've just tried cnn.com and github.com and those also show the same error.

**Comment by tenox7** [comment]
hmm this is very interesting, can you tell me which platform you're running wrp on?

**Comment by fergycool** [comment]
The browser is Classilla running on macOS9 (G4 Mac Mini). WRP is running as a docker container started with Docker Compose (including Netatalk). Host OS is Debian Bookworm. Please let me know if I can run anything differently to try to debug. I'm assuming this is just a problem for me?

**Comment by tenox7** [comment]
This is a very good information. Thank  you! I suspect that perhaps there could be an issue with ca-certs inside Docker container, while using html2markdown instead of Chrome. I have not tested text mode inside docker to be honest, so this may be a problem for everyone.  I will investigate this further!

**Comment by tenox7** [comment]
I think its fixed now?
can you try v4.7.2 or tenox7/wrp:latest from docker hub?
thank you!
