### ISSUE TITLE
Feature Request: Allow different image output formats

### ISSUE THREAD

**Issue by claunia** [tenox7/wrp#14]
- [x] Check GIF support status under PyQT4
- [x] Enable JPEG output under PyCocoa
- [x] Add PNG support
- [ ] Add BMP support
- [ ] Enable detection of browser and choose best format supported by it

**Comment by tenox7** [comment]
Remember that here we have one giant image for a whole web page, an important factors to consider are memory usage on the client side, loading and rendering time, perhaps we could test on some of the systems. I recall from '92 loading and displaying large jpeg images in a web browser took quite bit of time and memory even on higher end machines.

**Comment by claunia** [comment]
I do remember that GIFs and PNGs were easier to load. JPEG compression is quite cpu expensive compared with lzw and deflate.
