### ISSUE TITLE
Feature Request: HTML Form Field Input Boxes

### ISSUE THREAD

**Issue by tenleftfingers** [tenox7/wrp#2]
A little bird told me this feature might happen in the future. So just to formalise interest in this feature... :)

**Comment by tenox7** [comment]
That is correct. Picidae.py indeed did have support for forms etc. and I think it can be supported in WRP as well. I will look in to that.

**Comment by tenleftfingers** [comment]
I'm happy to test anything in development.

**Comment by tenox7** [comment]
not yet but I'm getting there :)

**Comment by tenleftfingers** [comment]
Don't give up!

**Comment by tenox7** [comment]
I'm not. I'm currently working in HTTPS/SSL problem which is much more crucial issue IMO.

**Comment by tenleftfingers** [comment]
I agree 100%. Great work tenox7. I’ll keep an eye.

**Comment by tenox7** [comment]
I have released a beta version of new WRP in GoLang using ChromeDP. The new protocol will open some doors and windows for input boxes. Namely chromedp supports clicking mouse and entering keystrokes programmatically. I will start working on this. In the mean time, there is another trick, you can run the new wrp in headed mode with `-h` flag. You can then login "on the server" and continue in already logged in session on in the legacy browser.

**Comment by tenox7** [comment]
This now has been implemented and is available as of 4.1 beta. Please download, check and report bugs! Thank you.
