### ISSUE TITLE
outdated urls in README

### ISSUE THREAD

**Issue by miniupnp** [tenox7/wrp#22]
both URLs http://virtuallyfun.superglobalmegacorp.com/2014/03/11/web-rendering-proxy-update/ and http://virtuallyfun.superglobalmegacorp.com/2014/03/03/surfing-modern-web-with-ancient-browsers/ point to 404 error pages.

**Comment by tenox7** [comment]
The links are in fact not outdated. The whole blog is down at the moment. The owner is traveling and can't easily fix it. It's supposed to be be back in a few days.

**Comment by miniupnp** [comment]
it works today

**Comment by tenox7** [comment]
yeah the site should be back and up
