### ISSUE TITLE
ImportError: No module named Foundation

### ISSUE THREAD

**Issue by brunocastello** [tenox7/wrp#25]
Hi, I've tried this on macOS High Sierra and got this error:

Traceback (most recent call last):
  File "wrp.py", line 516, in <module>
    import Foundation
ImportError: No module named Foundation

What should I do? There is not even instructions on how to run this. Thanks

**Comment by tenox7** [comment]
this could be because you have non-apple version of python https://stackoverflow.com/questions/1614648/importerror-no-module-named-foundation

**Comment by brunocastello** [comment]
@tenox7 you're right, I managed to get the apple version of python working again and finally ran the script.

For a test, I just set up a HTTP web proxy on my host OS (macOS High Sierra) before trying out on my guest OS (Windows 3.11 For Workgroups, Virtualbox VM). No website is being loaded, just the https ones are. This is the output from terminal:

Web Rendering Proxy v2.0 serving at port: 8080
127.0.0.1 - - [26/Aug/2018 16:58:37] code 501, message Unsupported method ('CONNECT')
127.0.0.1 - - [26/Aug/2018 16:58:37] "CONNECT d.dropbox.com:443 HTTP/1.1" 501 -
>>> URL request... http://oldweb.today/

Apparently python is crashing?

**Comment by brunocastello** [comment]
Actually, for some strange reason, it started working on my guest OS. Hooray...

**Comment by tenox7** [comment]
Unsupported method ('CONNECT') is to do with HTTPS support. As 99% of the web converted to https in last couple of years everything stopped working. I'm adding https support to wrp.

**Comment by brunocastello** [comment]
@tenox7 : Brilliant, I hope you can manage to do it. BTW, on another subject, I am with a strange problem. Maybe you can help - you seem to know a lot on this. 

I am trying to run a script from this guy (https://mainframed767.tumblr.com/post/164524161692/dosbox-and-trumpet-winsock-together-at-last) to allow Win 3.11 internet access on DOSBox. It does not work on neither OSX and Linux. 

Someone then updated it for both OSes (https://github.com/knightmare2600/oldschool/blob/master/WFW/dosbox_ppp.sh). Still, only works on my Raspbian after adding the following rules:

:: Allow established connections
  iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
  iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT

  :: Masquerade
  iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE

Then it began working. The problem: I am on a macbook air (macOS High Sierra) and it does not work because of these three lines above (I think so). I don't know what are the mac equivalents for these lines. I know macOS does use PF instead of IPTABLES, but I don't know how to "translate" them. I was wondering if you know?

**Comment by tenox7** [comment]
BTW I'm currently rewriting WRP in Go and more like browser inside a browser (no proxy). This will allow to deal with SSL issues better. I'm closing this for now, but stay tuned for the new version.
