### ISSUE TITLE
Need help with building a hosted proxy

### ISSUE THREAD

**Issue by ssshake** [tenox7/wrp#28]
Boring life story: I made a project that lets you browse archive.org's way back machine on old browsers. http://theoldnet.com

People are using it and cool sites are bubbling to the top. It's legit fun and I'm pretty happy with it. 

Want: I want to offer up the work you've done BUT allow users a configuration/setup free solution to browse modern web pages on old systems. 

Requirement: A similar experience with http://theoldnet.com. A user goes there, it loads up no problem (because no modern js/css). They type in their destination, they get a compatible response back. No need to enter browser proxy settings. No need to stand up their own server.

Ask: I'm not very experienced with python so although I'm sure what I'm asking is a not that much work, I don't know how to implement it off hand.

The end goal would be a python process that I could server through an nginx proxy. It takes an address as a param. Then does the heavy lifting you wrote. Then returns the response. And repeat.

**Comment by tenox7** [comment]
Yeah, originally WRP operated as browser inside browser which is more like what you are looking for. New version of WRP I'm currently writing will operate in this platform. You will be able to host it yourself somewhere and point people to it. Stay tuned.

**Comment by tenox7** [comment]
Please check the latest version which supports browser-in-browser. You just point your browser to it. Let me know if this works.

**Comment by ssshake** [comment]
Awesome that you, will check it out!

**Comment by tenox7** [comment]
Feel free to re-open this if needed.
