### ISSUE TITLE
Could not connect to display?

### ISSUE THREAD

**Issue by kyle2000yt** [tenox7/wrp#29]
I installed a fresh copy of Ubuntu Server 18.10 64bit, and ran THESE commands:
`sudo apt install sslstrip`
`sudo apt install python-pyqt5.qtwebki`
`git clone https://github.com/tenox7/wrp.git`
But when I run it, it does this:
![vmware_1LkP4sWLnf](https://user-images.githubusercontent.com/35104994/55493230-928cbc00-5606-11e9-9259-03f8fe4c2cd8.png)
I am running this in a VM.

**Comment by tenox7** [comment]
You need X11 installed and running.
