### ISSUE TITLE
Feature request: ISMAP support

### ISSUE THREAD

**Issue by tenox7** [tenox7/wrp#3]
ISMAP aka Server Side Image Map support 
Mosaic 1.x and IBM Web Explorer require it

**Comment by tenox7** [comment]
Mostly complete in Dev branch OSX version. 
Needs some cleanup and more testing, particularly on Mosaic and IBM Web Explorer.
Needs port to Linux-QT version.

**Comment by claunia** [comment]
Only needs testing on Mosaic and IBM WE.
