### ISSUE TITLE
linux env

### ISSUE THREAD

**Issue by pouledodue** [tenox7/wrp#31]
hi
I tried installing on some different linux versions and it always fails
Can you share on what distribution and version you installed it?
version of openssl also?

**Comment by Hubcapp** [comment]
works for me on debian stretch. openssl 1.1.0j-1~deb9u1

**Comment by tenox7** [comment]
Also please share the error message you are getting.

**Comment by tenox7** [comment]
I'm closing this as unable to reproduce. Also GoLang version of WRP will have zero dependencies like that.
