### ISSUE TITLE
Firefox can't connect to proxy. How to run and test the beta?

### ISSUE THREAD

**Issue by tenleftfingers** [tenox7/wrp#43]
I don't know what I'm doing wrong. I'm running Xampp/Apache on MacOS. I've created a php file called test.php which executes wrp-macos like this:

<?php

exec("./wrp-macos");

?>

I open that URL on safari to execute wrp-macos.

On Firefox settings, I've set the proxy to be the IP of the server on port 80, where wrp-macos is running. 

When I enter any URL, the browser complains that it "can't connect to the server" and that I should check my internet connection. Help?

**Comment by tenox7** [comment]
I think you missed the step showing how you execute it. 

Generally WRP 3.0 currently is not a "real proxy" due to (mostly) https/ssl issues. Proxy mode is in design/testing at the moment.

How you use WRP 3.0 is to launch it on some host and navigate your browser to it's adderss/port. Just like you would to Apache. Then you operate using WRP's own web page. It's basically a web server atm.

**Comment by tenleftfingers** [comment]
I did, thanks for the clarification. It's actually very simple in that case.

One request; it would be nice if when the terminal tells me the port (8080), it also reported the IP address.
![image](https://user-images.githubusercontent.com/1757768/59270084-8e090300-8c48-11e9-94f2-a001bb89ed20.png)

**Comment by tenox7** [comment]
Yeah I was thinking about it myself when coding, however the problem is that unless specified by you using `-l` the server listens on all IP addresses in the host. I guess I could enumerate and print all IP addresses found.

**Comment by tenleftfingers** [comment]
Well, it's working for me on MacOS with an Amiga browser as the client, many thanks! I would make one suggestion. Under the heading "Usage", the first instruction given is "Download a WRP binary and run on a server/gateway". My problem was that I was trying to create a server to run it on.

It might be more accurate/clear to say to download the binary "and run it from a terminal". But my question is answered and can be closed.

**Comment by tenox7** [comment]
When on Windows for example you can just double click on the exe to run it. So it wouldn't be best usage instruction. But I updated it to be more clear :)

BTW can you send some screenshots from Amiga?
