### ISSUE TITLE
Cookies authorization button does not work

### ISSUE THREAD

**Issue by lvcabral** [tenox7/wrp#44]
Some websites request an authorization for cookies and shows a button to the user to authorize, the WRP correctly maps the link but nothing happens after the click. One website it happens: www.modularmining.com

**Comment by tenox7** [comment]
Ack. Let me look on what can be done about it.

**Comment by tenox7** [comment]
this is now fixed in head:clicky and a new release 4.0 is available for testing https://github.com/tenox7/wrp/releases/tag/4.0
