### ISSUE TITLE
Putting Russian string into the search box brings garbage

### ISSUE THREAD

**Issue by Anixx** [tenox7/wrp#46]
Google results are shown in incorrect encoding. In other places Russian also does not work. Why do not just use Unicode?

![Clipboard_20190617 (2)](https://user-images.githubusercontent.com/1271736/59601136-d4100c00-910b-11e9-9cef-175d70c49e7b.png)

**Comment by tenox7** [comment]
can you try with latest verion? works fine for me

**Comment by tenox7** [comment]
Closing since there is no update. I was not able to reproduce.
