### ISSUE TITLE
Cannot move to a next page in Google search results.

### ISSUE THREAD

**Issue by Anixx** [tenox7/wrp#47]

**Comment by tenox7** [comment]
This normally works just fine. Please provide more details. Client browser, platform on which wrp is running, etc.

**Comment by Anixx** [comment]
For instance, in Netscape Navigator 1.0, clicking on the second "O" or a number under it still reloads the first page.

**Comment by tenox7** [comment]
oh.. this is not a next page in WRP but second page in Google right?

**Comment by Anixx** [comment]
Yes, the second page in Google search results.

**Comment by tenox7** [comment]
Confirmed.

**Comment by tenox7** [comment]
This is now fixed in 4.0 preview. https://github.com/tenox7/wrp/releases/tag/4.0
