### ISSUE TITLE
[Bug] [V4.1] Wikipedia shows as a blank page

### ISSUE THREAD

**Issue by tenleftfingers** [tenox7/wrp#51]
System: MacOS 10.11.6
Browser: Safari 11.1.2

Entering "https://en.wikipedia.org" as the URL results in a blank page/image.

Same problem with https://google.ie

**Comment by tenox7** [comment]
Please provide more details. Which platform is WRP running on, also whats is the platform and web browser for a client.

**Comment by tenleftfingers** [comment]
Updated.

**Comment by tenox7** [comment]
Thank you! Can you also provide log output from WRP?
Also did you press enter after entering the url or press Go button with mouse?

**Comment by tenleftfingers** [comment]
My pleasure :) Here is the output for one attempt using the Go button with mouse and another attempt pressing Enter.

Last login: Fri Jul 12 19:47:05 on ttys000
You have new mail.
Aislings-MacBook-Pro:~ jarlath$ Downloads/wrp-macos 
2019/07/12 20:18:02 Web Rendering Proxy Version 4.1
2019/07/12 20:18:02 Starting WRP http server on :8080
2019/07/12 20:18:07 [::1]:59736 Page Request for / []
2019/07/12 20:18:07 WrpReq from Form: &{U: W:1152 H:600 S:1 C:256 X:0 Y:0 K: B:false}
2019/07/12 20:18:15 [::1]:59749 Page Request for / [url=https%3A%2F%2Fen.wikipedia.orgdia.org&w=1152&h=600&s=1.00&c=256&k=]
2019/07/12 20:18:15 WrpReq from Form: &{U:https://en.wikipedia.orgdia.org W:1152 H:600 S:1 C:256 X:0 Y:0 K: B:false}
2019/07/12 20:18:15 [::1]:59749 Processing Capture Request for https://en.wikipedia.orgdia.org
2019/07/12 20:18:20 [::1]:59749 Landed on: chrome-error://chromewebdata/
2019/07/12 20:18:20 [::1]:59749 Encoded GIF image: /img/4171.gif, Size: 1KB, Colors: 256
2019/07/12 20:18:20 [::1]:59749 Done with caputure for chrome-error://chromewebdata/
2019/07/12 20:18:20 [::1]:59749 IMG Request for /img/4171.gif
2019/07/12 20:18:38 [::1]:59749 Page Request for / [hist=Back&url=https%3A%2F%2Fen.wikipedia.orgdia.org&w=1152&h=600&s=1.00&c=256&k=]
2019/07/12 20:18:38 WrpReq from Form: &{U:https://en.wikipedia.orgdia.org W:1152 H:600 S:1 C:256 X:0 Y:0 K: B:true}
2019/07/12 20:18:38 [::1]:59749 History Back
2019/07/12 20:18:42 [::1]:59749 Landed on: about:blank
2019/07/12 20:18:42 [::1]:59749 Encoded GIF image: /img/4607.gif, Size: 1KB, Colors: 256
2019/07/12 20:18:42 [::1]:59749 Done with caputure for about:blank
2019/07/12 20:18:42 [::1]:59749 IMG Request for /img/4607.gif

**Comment by tenox7** [comment]
OK so clicking enter presses history back button which gets you to about:blank. I'm going to move this button past Go maybe.

However from the log looks like you are trying to go to `https://en.wikipedia.orgdia.org` which then goes to chrome error page.

**Comment by tenleftfingers** [comment]
Okay.

Strange URL. I don't know why the string would change like that.

**Comment by tenox7** [comment]
I have not tested on Mac much so I'm very curious if it works or not.

**Comment by tenleftfingers** [comment]
You're right, I had entered the wrong URL one time. But the other times it was correct and I got a blank page. Here is more output and please feel free to ask for more details if you need:

$ Downloads/wrp-macos 
2019/07/13 18:01:25 Web Rendering Proxy Version 4.1
2019/07/13 18:01:25 Starting WRP http server on :8080
2019/07/13 18:01:30 [::1]:49931 Page Request for / []
2019/07/13 18:01:30 WrpReq from Form: &{U: W:1152 H:600 S:1 C:256 X:0 Y:0 K: B:false}
2019/07/13 18:01:41 [::1]:49940 Page Request for / [hist=Back&url=https%3A%2F%2Fen.wikipedia.org+&w=1152&h=600&s=1.00&c=256&k=]
2019/07/13 18:01:41 WrpReq from Form: &{U:https://en.wikipedia.org  W:1152 H:600 S:1 C:256 X:0 Y:0 K: B:true}
2019/07/13 18:01:41 [::1]:49940 History Back
2019/07/13 18:01:45 [::1]:49940 Landed on: about:blank
2019/07/13 18:01:46 [::1]:49940 Encoded GIF image: /img/8489.gif, Size: 1KB, Colors: 256
2019/07/13 18:01:46 [::1]:49940 Done with caputure for about:blank
2019/07/13 18:01:46 [::1]:49940 IMG Request for /img/8489.gif

**Comment by tenox7** [comment]
From the last log looks like you are still going to about:blank with history back button. Are you sure you are clicking Go button? The log indicates that you pressed the back button.

Also try the latest release 4.2 which has back button moved to the right.

**Comment by tenleftfingers** [comment]
I've just tried again. I am pressing 'Return' after entering the URL (https://en.wikipedia.org).

$ Downloads/wrp-macos 
2019/07/14 20:34:40 Web Rendering Proxy Version 4.1
2019/07/14 20:34:40 Starting WRP http server on :8080
2019/07/14 20:34:45 [::1]:58280 Page Request for / []
2019/07/14 20:34:45 WrpReq from Form: &{U: W:1152 H:600 S:1 C:256 X:0 Y:0 K: B:false}
2019/07/14 20:34:59 [::1]:58320 Page Request for / [hist=Back&url=https%3A%2F%2Fen.wikipedia.org&w=1152&h=600&s=1.00&c=256&k=]
2019/07/14 20:34:59 WrpReq from Form: &{U:https://en.wikipedia.org W:1152 H:600 S:1 C:256 X:0 Y:0 K: B:true}
2019/07/14 20:34:59 [::1]:58320 History Back
2019/07/14 20:35:04 [::1]:58320 Landed on: about:blank
2019/07/14 20:35:05 [::1]:58320 Encoded GIF image: /img/0237.gif, Size: 1KB, Colors: 256
2019/07/14 20:35:05 [::1]:58320 Done with caputure for about:blank
2019/07/14 20:35:05 [::1]:58320 IMG Request for /img/0237.gif

**Comment by tenleftfingers** [comment]
It works with 4.2. I can view Wikipedia and Google by entering the URL. Both the Go button and just pressing return work.

**Comment by tenox7** [comment]
Great to hear that :)
