### ISSUE TITLE
not working on IOS 5 (iPad 1)

### ISSUE THREAD

**Issue by ido370** [tenox7/wrp#53]
Web rendering proxy is running on Windows 10 Pro. I can open the webpage at port 8080 (on iPad), but after filling in a url and clicking GO, the website does not show on the iPad 1.

**Comment by tenox7** [comment]
Can you please attach logs from wrp? Thanks!

**Comment by ido370** [comment]
> Can you please attach logs from wrp? Thanks!

yes, where can i find it on windows version. i only have the exe file which i run, i dont see a log being written?

**Comment by tenox7** [comment]
Instead of running .exe file by double clicking, open cmd / command prompt window and run it from there. It should start printing log messages there.
