### ISSUE TITLE
gif image doesn't render in some browsers

### ISSUE THREAD

**Issue by tenox7** [tenox7/wrp#54]
gif image doesn't render in `omniweb`, also `xv` image viewer and all graphical software on SGI IRIX

suspected issue with LZW compression

**Comment by parkerlreed** [comment]
You can add Internet Explorer on Windows Mobile to that list. Just get the little broken image icon.

**Comment by tenox7** [comment]
Thank you! Which version of IE and Windows Mobile is this?

**Comment by parkerlreed** [comment]
Scratch that. The default settings had image loading disabled (even though it would load some images anyways).

**Comment by tenox7** [comment]
haha cool

**Comment by tenox7** [comment]
upstream issue https://github.com/golang/go/issues/33748

**Comment by tenox7** [comment]
as a workaround for omniweb at least added `-t png` flag which omniweb 3.0 renders correctly

**Comment by pomosapiens** [comment]
can confirm `-t png` works for OmniWeb 2.7b3 on NEXTSTEP 3.3 inside VirtualBox.

**Comment by rhaleblian** [comment]
![Screen Shot 2021-09-18 at 11 24 10 AM](https://user-images.githubusercontent.com/94912/133894849-9faba958-c55b-4df8-b43c-203d04087a37.png)
( posting for @pomosapiens )

**Comment by tenox7** [comment]
The upstream issue has been fixed and closed. I'm going to wait for release of new go compiler and library and update wrp.

**Comment by tenox7** [comment]
updated to latest chromedp, haven't tested but it should work
