### ISSUE TITLE
[Suggestion] Interface

### ISSUE THREAD

**Issue by mindingulove** [tenox7/wrp#58]
IS there any way of making url space wider and rearrange the buttons to a better layout?
 That way I can simply hide address bar and favourites from browser and get a better aesthetic.
THX

**Comment by tenox7** [comment]
Very good suggestion. Have a look at https://github.com/tenox7/wrp/blob/eb4201c56bc51e915d7a737d81b7c2c15f9d5a61/wrp.go#L84 It's a simple HTML that you can edit. When you come up with something better please send a PR and I will merge to WRP. 

Also think about how to make it more customizable for users. Perhaps a flag could be added that would allow custom html from file or something like that?

**Comment by tenox7** [comment]
Also looking at the interface, perhaps multiple input boxes for Width, Height, Colors and Scale could be combined in to one input box with certain text format? Eg:

```
1024x768x256x1.0
```

?

**Comment by mindingulove** [comment]
I suggest the following



```
<form action="/" method="POST">
<input type="SUBMIT" name="Fn" value="<"><input type="SUBMIT" name="Fn" value="Bk"><input type="SUBMIT" name="Fn" value=">" size="1"><input type="TEXT" name="url" value="" size="90">
<input type="SUBMIT" value="Go">&nbsp; text<input type="TEXT" name="k" value="" size="4">
W <input type="TEXT" name="w" value="1152" size="4"> 
H <input type="TEXT" name="h" value="600" size="4"> 
S <input type="TEXT" name="s" value="1.00" size="3"> 
C <input type="TEXT" name="c" value="256" size="3"> 
<input type="SUBMIT" name="Fn" value="Bs">
<input type="SUBMIT" name="Fn" value="Rt">

<input type="SUBMIT" name="Fn" value="^">
<input type="SUBMIT" name="Fn" value="v">

</form>
```

**Comment by tenox7** [comment]
Several issues. First of all, as is such a very long input box would not fit on a very small screen of a vintage computer. Also < > unquoted in name is not allowed in HTML. Quoted like &gt; or &lt; are ok but they will not render on several old browsers.

I'm now thinking that perhaps a good option would be to move W, H, S, C, to a separate settings/preferences page where you could set these and then they would be carried over as hidden form entry on the normal page. This would create more room for longer url box and home/back/forward buttons. Let me work something out.

**Comment by tenox7** [comment]
I made some small fixes in head/master you may like it.

**Comment by brunocastello** [comment]
I believe vintage browsers can understand very basic and old plain javascript. That said, can't we make the input field change according to the type of field (textarea for big texts, inputs for smaller fields) ?

**Comment by tenox7** [comment]
Most certainly the browsers that I mostly use do not understand any JavaScript. Can you elaborate more about the feature request? You just want the text field to get bigger?

**Comment by brunocastello** [comment]
> Most certainly the browsers that I mostly use do not understand any JavaScript. Can you elaborate more about the feature request? You just want the text field to get bigger?

For example, sending an email on Gmail. when the field is the message, change the input to a textarea type field, slightly bigger, and when the field is the input "To", or "Subject" change to a normal input text type field. Things like that would make it easier to use. Because typing an email or a forum reply using the tiny input field is... tiny. Sry, I can't explain better than that.

**Comment by tenox7** [comment]
Understood. For purpose of WRP I would assume no JS in browsers. What I can make is perhaps the input field bigger or more customizable perhaps?

**Comment by brunocastello** [comment]
> Understood. For purpose of WRP I would assume no JS in browsers. What I can make is perhaps the input field bigger or more customizable perhaps?

I'm not really sure. I understand your point on why no JS - And I appreciate that, since I hate jQuery, modern JS frameworks - but I also understand that even Win 3.x browsers were capable of understanding some very early vanilla JS. And I mean, really early vanilla JS, and that was a good thing back then.

A better option would be using a textarea only instead of an input. Then the user can resize it as he wants to, so he can see better what he's typing on. Shouldn't require JS.

**Comment by tenox7** [comment]
The first version of JavaScript came out in Netscape Navigator 2.0 in 1995. There are several browsers that I officially support and use, released before that. For example Mosaic.

Textarea sounds good. I will investigate!

**Comment by brunocastello** [comment]
You could make an option before the compile to choose between JS or no JS solution. That way you'd have better support for "newer" old browsers, and still support no-JS for "older" old browsers. Just my .5 cents

**Comment by brunocastello** [comment]
I actually had a brilliant idea for more modern, old vintage browsers though, aimed at Windows 9x, for example, like Mozilla browsers (Firefox, Netscape 9, SeaMonkey). How about a browser extension ?? This way with a browser extension we can have the same controls on toolbar, hiding the controls on page? How cool it could be? I do not know how to make an extension, though, the best help I can offer is an attempt to make the toolbar look more like the browsers interface. I can have a go at it when I have some free time (I had, but today was my last day of vacation, so...)

**Comment by Madis0** [comment]
As if legacy browsers had good extension support... No, you'd have to support old, dead, complex code which is absolutely not worth it.

Better just make some variants of the "browser" HTML that are changeable via GET query.

**Comment by tenox7** [comment]
Yeah I really don't want to maintain a list of what browsers supported what or trying to detect it. This is  one of reasons why JQuery came to be.

I would consider adding an option to enable/disable some basic JS kind of like we have GIF/PNG. However could you specify in more details what would the JS do? In particular is this just about arranging size of the fields? If so why don't we parametrize these, or maybe add a flag to load custom HTML template from file instead of built-in? You can then arrange it all the way you want and even include JS if you want. I think I will do that.

**Comment by brunocastello** [comment]
I think it can work. As a template, so one can create a design similar to the one used by the browser, hide the original toolbar, and use it as main toolbar. Without this parameter specified, defaults to original design. Should be easier for starters, some of us should know how to edit them.

I also agree with the jQuery comment. Today, modern browsers can support all the same features and now it isn’t much needed, however developers became too much dependent of it and did not learn very basic vanilla JS at least. It’s hard for them to abandon it. And we now have Angular, React, Vue... oh dear.

**Comment by tenox7** [comment]
okay I have checked in an update to wrp that allows user to customize the ui using wrp.html template file

this of course requires some testing so it's not released yet, you will need to get the latest head master / git clone the repository and build / run locally

note wrp.thml file is an example/default html template you can modify it to your needs

please let me know any issues!

**Comment by tenox7** [comment]
okay ui customization is now officially released in 4.5.2
please try it and reopen this issue as needed
https://github.com/tenox7/wrp/releases/tag/4.5.2

**Comment by brunocastello** [comment]
Will try it later. I have seen other solution called Browservice that has a great UI to replace the browser bar, if we manage to mimic the same UI idea, it would be perfect.

**Comment by tenox7** [comment]
Browservice is targeting browsers that have JS and CS so you can style something nice. I mostly work with browsers that have none of these. Perhaps different template html files could be made for different vintages of browsers.

**Comment by tenox7** [comment]
I opened another ticket for the UI. Perhaps you could contribute a better UI for WRP by submitting more UI html template files?
