### ISSUE TITLE
FATAL: cpu lacks required instruction sets on an older Xeon server + Docker

### ISSUE THREAD

**Issue by Scoth42** [tenox7/wrp#59]
Greetings,

I'm attempting to run this on an older Xeon (X5650) server. If I download a binary and run it, it runs just fine. Trying to run the docker image from the docker hub generates an error, "FATAL: cpu lacks required instruction sets". As near as I can tell from docker hub it should support AMD64; is there some other dependency in there that doesn't get along with the processor in this?

**Comment by tenox7** [comment]
Hi, this is very interesting. Do you have any logs that would show which CPU instruction is missing? Can you look in docker logs?

**Comment by Scoth42** [comment]
I'm a bit of a noob to Docker so if there's a better way to get logs out of it I can try it, but doing a docker logs on the container just gives me the fatal line above, and I'm not seeing anything specific in the docker logs. I did try a few things to access the stopped container such as starting it with a different command line and got the same error.

**Comment by tenox7** [comment]
We should first narrow it down a bit before going in to specifics. Can you try to run the linux binary outside of docker and see if it starts? You can

```
curl -LO https://github.com/tenox7/wrp/releases/download/4.4/wrp-amd64-linux
chmod 755 ./wrp-amd64-linux
./wrp-amd64-linux
```

See if it starts or throws any errors.

**Comment by Scoth42** [comment]
Yep, that's what I tried first and it worked fine

**Comment by tenox7** [comment]
Upon little investigation this is probably to do with how the original chromedp container is build and even more likely with chrome browser is built. I think perhaps upstream ticket with chromedp is in order.

**Comment by tenox7** [comment]
I'm going to close this, please feel free to reopen if this is still an issue.
