### ISSUE TITLE
Feature request: image postprocessing

### ISSUE THREAD

**Issue by tenox7** [tenox7/wrp#7]
Allow image post-processing with **ImageMagic** for better compression, dither, color palette, color quantitization (MagickQuantizeImage  quantizeDither), etc. This is to reduce image size and memory footprint on ancient systems with little memory.

Possibly use PythonMagick (http://stackoverflow.com/questions/1740158/documents-and-examples-of-pythonmagick).

**Comment by miniupnp** [comment]
is that possible to merge the "Dev" branch ?
Or are things missing ?

**Comment by antonipx** [comment]
I think it hasn't been thoroughly tested. Have you used the dev branch? If everything works we can merge.

**Comment by tenox7** [comment]
From what I can see PyQt4 is almost unusable right now so we need to update to PyQt5 to even test dev branch.

**Comment by claunia** [comment]
@tenox7 -dev is working for me in ArchLinux with PyQt5 and ImageMagick, as long as the site doesn't auto-redirect to HTTPS.
