### ISSUE TITLE
*BSD Support

### ISSUE THREAD

**Issue by VENTDEV** [tenox7/wrp#70]
Not sure why there was a decision to drop support for BSDs. I assume it's because of the switch to Chrome as a backend? Was there any technical reason you all couldn't use a FOSS browser backend like Chromium? I find it a silly choice to force a proprietary web browser maintained by an advertising agency to use a piece of FOSS software. Any chances of getting a Chromium backend, and thus eventually a FreeBSD version again?

**Comment by tenox7** [comment]
I don't know what are you talking about. Chromium and Chrome are the same browser maintained by the same advertising agency. Those are the differences: https://chromium.googlesource.com/chromium/src/+/master/docs/chromium_browser_vs_google_chrome.md - the main being color of the logo. I also don't understand by dropping support for FreeBSD? WRP supports all OSes that Golang supports and can run Chrome or Chromium.

If you find any of my choices silly there is a little button called Fork on the top right. Make your own fork with your own silly choices. This is how FOSS works.

**Comment by VENTDEV** [comment]
> I also don't understand "dropping support for FreeBSD"? WRP supports all OSes that Golang supports and can run Chrome or Chromium.
> 

According to the readme, it says it only supports Chrome. Which doesn't work on the BSDs as you well know.

Also the text about FreeBSD was removed from the readme.

What I did not see is that you do have packages in the WRP Binary section, so I stand corrected, there is FreeBSD support. Sorry, I checked FreeBSD repos and then checked your Git page, and saw no mention of FreeBSD support anymore.

**Comment by tenox7** [comment]
I will update the readme to include Chromium. Thats fair.

**Comment by VENTDEV** [comment]
Thanks! It should clear up some confusion. At least from me. :)

**Comment by tenox7** [comment]
Okay looks like the issue has been resolved.

**Comment by VENTDEV** [comment]
Thanks much!
