### ISSUE TITLE
Feature: Able to send keyboard input on top bar without "enter" key

### ISSUE THREAD

**Issue by mrneo240** [tenox7/wrp#74]
This is fantastic so far for older devices to browse the web with over dialup.

It would be really nice if there was a way to submit text without having to use a physical enter key because these devices do not have one.

A possible solution would be to always check and send text input if present in the form or to add a button that would just allow you to send without changing other parameters. This might also go well with the external html header feature in #69

**Comment by tenox7** [comment]
Hi thanks for the suggestion. The button labelled "Rt" is is for that. Or do you have something else in mind? Perhaps it's mislabelled and should be "Ent" or something like that?

**Comment by mrneo240** [comment]
I have tried that and I still am not able to enter text with the input box, 
I am not very familiar with Golang but it would appear here 
[https://github.com/tenox7/wrp/blob/master/wrp.go#L256](https://github.com/tenox7/wrp/blob/master/wrp.go#L256)

that by using the "Rt" button the execution flow would not reach the part where it sends the keyboard input from the textbox. 

That is my issue, i have no way to submit that form without satisfying the earlier two conditions.

**Comment by tenox7** [comment]
yeah I think that code needs refactoring for readability

also my bad, instead of Rt can you try pressing Go?, so tap mouse on input box, type something in the K field then press Go instead of Rt, let me know if it works

**Comment by tenox7** [comment]
I'm going to close this as this essentially work just there was a confusion with button names. Please feel free to re-open as needed.
