### ISSUE TITLE
WRP hangs at "Starting WRP http server"

### ISSUE THREAD

**Issue by MarshmelloSUCKS** [tenox7/wrp#75]
Whenever I try to start WRP via Docker or the Linux binary, it always hangs at "Starting WRP http server on :8000". Both Chromium and Go are installed. I've tried running with `sudo` and that doesn't seem to work either. Using Pop!_OS 20.04

**Comment by tenox7** [comment]
Hi, can you elaborate on hanging? That message basically indicates that the server is started and you can connect to it. What happens when you connect to your IP address on port 8080 (or whatever port your configured). Thanks

**Comment by MarshmelloSUCKS** [comment]
Sorry for not replying in forever. I've updated to Pop!_OS 20.10 and it works fine now.
