### ISSUE TITLE
[Suggestion] replace "<^v>" with "←↑↓→"

### ISSUE THREAD

**Issue by wojtekpolska** [tenox7/wrp#79]
Since these arrows behave like normal characters (they are ASCII not emojis/emoticons) they will work on even the oldest systems

I personally think the look better, because they are all equal shape, while current ones are greater/lesser than signs, caret and a letter V

I even checked and they were available in the very 1st version of Unicode ( https://www.unicode.org/Public/reconstructed/1.0.0/UnicodeData.txt ) 
so they should be displayed properly even by the oldest browsers in existence :)

I got inspired by this: https://en.wikipedia.org/wiki/Template:Keyboard

**Comment by tenox7** [comment]
will they render in Mosaic 0.6B ?

**Comment by wojtekpolska** [comment]
@tenox7 Im confident that they will

i couldn't test for myself but i dont really see a way it wouldn't

btw. i found suprisingly little information about this browser so now im curious about it 

but really i think it will render in any browser there is. 

what did it even run on because i didnt find much information about this browser

**Comment by tenox7** [comment]
I'm actually pretty sure they won't work. I don't think old browsers supported Unicode in any shape or form.

**Comment by wojtekpolska** [comment]
I think these arrows were introduced even before unicode but im not certain about that

i guess only way is to try out. maybe you can throw that in next time you will test some changes there 

These arrows were really introduced long long ago so maybe they'll be supported

**Comment by wojtekpolska** [comment]
@tenox7 turns out you were right. Using waybackmachine i managed to load old version of wikipedia page with this stuff

![image](https://user-images.githubusercontent.com/58272360/99138235-8add2800-262f-11eb-8ecd-178c7e6e9279.png)

**Comment by tenox7** [comment]
I did try &gt; &lt; in the past even that didn't work.

BTW you can find Mosaic archives here: https://ftp.icm.edu.pl/packages/Mosaic/

**Comment by tenox7** [comment]
I'm also thinking about disabling arrows in the default UI since they have very little use

**Comment by wojtekpolska** [comment]
like the browsers just displayed & gt as text?

**Comment by wojtekpolska** [comment]
also i think its good to keep them, since they don't cause problems and imo its work keeping them even for these 3 peoples who will use them
