### ISSUE TITLE
Prioritize high-contrast colours when using GIF and low palette counts

### ISSUE THREAD

**Issue by tomrow** [tenox7/wrp#80]
When using the GIF encoder with a low number of colours, pictures on the page window can make the text look light grey/beige, blurry and somewhat hard to read. I think prioritizing black and white in the palette generation process might help with this a bit.

**Comment by tenox7** [comment]
Thats a very good idea. Do you know how to do it, or best could you send a PR with this?

**Comment by tenox7** [comment]
@tomrow hey I'm going to be doing a new release, do you know how to change palette prioritization easily?

**Comment by tomrow** [comment]
Unfortunately I don't know how to program in Go, so I can't give any code suggestions. Perhaps you could force the quantiazer to use a set palette, or perhaps change the image contrast before quantization?

**Comment by tenox7** [comment]
The latest build has completely changed how gifs are encoded and palletized. Hopefully for the better. It would be awesome if you could try it and let me know.

**Comment by tomrow** [comment]
This is great! 2 and 4- bit modes have much higher contrast dark gray text now, rather than the odd oranges and blues of before.

**Comment by tenox7** [comment]
Cool thanks!
