### ISSUE TITLE
[Bug] Keystrokes are not working in a specific browser. 

### ISSUE THREAD

**Issue by wojtekpolska** [tenox7/wrp#81]
Hi i was using your program and its great! but for some reason keystroke function is not working in "Internet Channel" for Nintendo Wii game console

Here is a video showing me try enter anything into google search bar: www.youtube.com/watch?v=Xds4Edq6VQI

PS: Sorry that im recording screen with a camera here, but this console nor this tv have a screen recording function. (also i filmed in portrait mode since I had to hold my phone in one hand to use the remote that uses motion controls in the other)

I also tried to input keystrokes in both PNG and GIF mode, and submitting the keystrokes by clicking either "GO" or "RT" keys but there is no difference. 

If this helps, Internet Channel was developed by Opera per Nintendo's request for Nintendo Wii in 2007 

Other person also tried WRP on Wii and had the same problem - they also couldn't input text. 

I don't know if this browser is within the scope of this project, but it would've been nice if WRP supported it. 

Internet Channel https://en.wikipedia.org/wiki/Internet_Channel 
Nintendo Wii https://en.wikipedia.org/wiki/Wii

**Comment by wojtekpolska** [comment]
@tenox7 Do you know if there is something possible to do? Is there any way i can solve it myself? 
I tried other browser and it worked fine but not this one

**Comment by tenox7** [comment]
Thats a very interesting issue. The problem is I don't have easy way of reproducing it. I actually sold my Wii a few years back on eBay. What I would like to see what happens to a cursor once you click on the input box. Your video glances over it little too quick. It would be critical to see. I think the input text box loses focus somehow. Also you can run wrp in headed mode that will show the chrome window and allow you to see whats happening exactly. Please do this and send more info.

**Comment by wojtekpolska** [comment]
@tenox7 sorry, how do i run wrp in headed mode? 

From readme i understood it's "-h" but im not sure where to put it? should i run wrp from command line with -h argument?

Also sorry that i forgot to check if you responded sooner. I can test what you asked tomorrow. thanks for answer!

**Comment by wojtekpolska** [comment]
@tenox7 I have no idea why, but it started to accept keystrokes, however ONLY when i do it in this order:
[message] > press enter on keyboard (not Rt in wrp) > GO 

Then it does work, but i think in other browser i tried, it also worked when i typed a message and clicked Rt in wrp

And also when i dont click enter after typing a message, it didnt work either (as in 1st video) 


I have no idea, im very confused. i will do more testing and tell you
