### ISSUE TITLE
wrp wont show the ip, just the port

### ISSUE THREAD

**Issue by BubblyPopper** [tenox7/wrp#84]
on the console wrp just shows the port and not the ip, what ip do i need to connect?

**Comment by tenox7** [comment]
Well that depends on what did you specify in `-l` flag. If you did not specify it, the default is "any IP address on your machine" with port `:8080`.

**Comment by techboyg5** [comment]
just a test comment on this issue, will be deleted right away.

**Comment by tenox7** [comment]
I have added printing all possible IP addresses the machine has if addr = ":" or "0.0.0.0:"
