### ISSUE TITLE
WRP 4.5.1 release for amd64-windows is actually 4.5

### ISSUE THREAD

**Issue by dakotaKat** [tenox7/wrp#86]
Was trying to troubleshoot why the prebuilt 4.5.1 release for windows amd64 wasn't giving me the wrp.html UI I configured -- turns out it seems to be the 4.5 release, as the 386 windows release happily takes the UI.

Can we get the correct release? Thanks! <3

**Comment by tenox7** [comment]
try 
https://github.com/tenox7/wrp/releases/tag/4.5.2
