### ISSUE TITLE
dyld: Symbol not found: _clock_gettime

### ISSUE THREAD

**Issue by piercingimpulse** [tenox7/wrp#91]
Hi
I'm receiving this error when I try to rung wrp on macOS 10.11

_dyld: Symbol not found: _clock_gettime
  Referenced from: /Users/leo/Downloads/./wrp-amd64-macos
  Expected in: flat namespace

Trace/BPT trap: 5_

I'm aware is because it is not on the SDK for El Capitan, therefore I've been running 4.5 version, but I would really like to have the latest version as way to customize wrp.html.

Also, I would really like to thank you for this project! I hope in the future to contribute somehow!

**Comment by tenox7** [comment]
Thanks for the report. I currently have no access to 10.11 handy. I can probably install it if needed but perhaps you could try to build it for it yourself? It's actually very easy. 

First go to https://golang.org/ and download / install Go.
Then you also need Git, there are many ways of getting git on Mac like Brew.
```
$ git clone https://github.com/tenox7/wrp.git
$ cd wrp
$ make
```

Let me know if it works or doesnt!

**Comment by piercingimpulse** [comment]
Hiya

Sorry if I came back this late!
Unfortunately it does not work, it still encounter the same error.
I'll see if I can find a workaround (:

**Comment by tenox7** [comment]
Closing this as there is no update. Please feel free to re-open if you can reproduce this.
