### ISSUE TITLE
Text boxes do not work

### ISSUE THREAD

**Issue by thetechknight** [tenox7/wrp#95]
Trying to log into 68kmla.org, and the login screen textboxes dont work. Clicking on them gives me a cursor, but typing does nothing. 

![image](https://user-images.githubusercontent.com/22461464/138594586-a12c52f4-29d6-4aba-8e2e-1d0de1b82270.png)

**Comment by tenox7** [comment]
just tried in latest version from head master and it's working just fine

just making sure, to type text in to the target text box you type it in the one between number of colors and Bs (your full login or email) then you click Go to actually send it.

Closing for now. If this still doesn't work please comment and I will reopen.
